import os
import logging
from typing import Dict, List

# Настройка логгера
logger = logging.getLogger(__name__)

# Базовый путь к логотипам
LOGOS_FOLDER = r"C:\1\logos"

# Маппинги команд по лигам
LEAGUE_TEAMS_MAPPINGS = {
    "Austria - Bundesliga": {
        "рапид": "Rapid Vienna.png",
        "рапид вена": "Rapid Vienna.png",
        "rapid vienna": "Rapid Vienna.png",
        "rapid wien": "Rapid Vienna.png",
        "ред булл зальцбург": "Red Bull Salzburg.png",
        "зальцбург": "Red Bull Salzburg.png",
        "red bull salzburg": "Red Bull Salzburg.png",
        "salzburg": "Red Bull Salzburg.png",
        "алтах": "SCR Altach.png",
        "scr altach": "SCR Altach.png",
        "аустрия клагенфурт": "SK Austria Klagenfurt.png",
        "клагенфурт": "SK Austria Klagenfurt.png",
        "sk austria klagenfurt": "SK Austria Klagenfurt.png",
        "austria klagenfurt": "SK Austria Klagenfurt.png",
        "штурм": "SK Sturm Graz.png",
        "штурм грац": "SK Sturm Graz.png",
        "sk sturm graz": "SK Sturm Graz.png",
        "sturm graz": "SK Sturm Graz.png",
        "хартберг": "TSV Hartberg.png",
        "tsv hartberg": "TSV Hartberg.png",
        "вольфсбергер": "Wolfsberger AC.png",
        "wolfsberger": "Wolfsberger AC.png",
        "wolfsberger ac": "Wolfsberger AC.png",
        "тироль": "WSG Tirol.png",
        "wsg tirol": "WSG Tirol.png",
        "rapid": "Rapid Vienna.png",
        "salzburg": "Red Bull Salzburg.png",
        "red bull salzburg": "Red Bull Salzburg.png",
        "sturm graz": "SK Sturm Graz.png",
        "austria": "Austria Vienna.png",
        "austria wien": "Austria Vienna.png",
        "austria vienna": "Austria Vienna.png",
        "blau-weiss linz": "FC Blau-Weiss Linz.png",
        "grazer ak": "Grazer AK 1902.png",
        "lask": "LASK.png",
    },
    "Belgium - Jupiler Pro League": {
        "беерсхот": "Beerschot VA.png",
        "beerschot": "Beerschot VA.png",
        "серкль брюгге": "Cercle Brugge.png",
        "серкл брюгге": "Cercle Brugge.png",
        "cercle brugge": "Cercle Brugge.png",
        "брюгге": "Club Brugge KV.png",
        "клуб брюгге": "Club Brugge KV.png",
        "club brugge": "Club Brugge KV.png",
        "club brugge kv": "Club Brugge KV.png",
        "дендер": "FCV Dender EH.png",
        "fcv dender": "FCV Dender EH.png",
        "dender": "FCV Dender EH.png",
        "гент": "KAA Gent.png",
        "аа гент": "KAA Gent.png",
        "kaa gent": "KAA Gent.png",
        "gent": "KAA Gent.png",
        "генк": "KRC Genk.png",
        "кrc генк": "KRC Genk.png",
        "krc genk": "KRC Genk.png",
        "genk": "KRC Genk.png",
        "кортрейк": "KV Kortrijk.png",
        "kv kortrijk": "KV Kortrijk.png",
        "kortrijk": "KV Kortrijk.png",
        "мехелен": "KV Mechelen.png",
        "kv mechelen": "KV Mechelen.png",
        "mechelen": "KV Mechelen.png",
        "вестерло": "KVC Westerlo.png",
        "kvc westerlo": "KVC Westerlo.png",
        "westerlo": "KVC Westerlo.png",
        "ауд-хеверле": "Oud-Heverlee Leuven.png",
        "левен": "Oud-Heverlee Leuven.png",
        "oud-heverlee": "Oud-Heverlee Leuven.png",
        "ohl": "Oud-Heverlee Leuven.png",
        "шарлеруа": "R Charleroi SC.png",
        "charleroi": "R Charleroi SC.png",
        "антверпен": "Royal Antwerp FC.png",
        "royal antwerp": "Royal Antwerp FC.png",
        "antwerp": "Royal Antwerp FC.png",
        "андерлехт": "RSC Anderlecht.png",
        "rsc anderlecht": "RSC Anderlecht.png",
        "anderlecht": "RSC Anderlecht.png",
        "сент-трюйден": "Sint-Truidense VV.png",
        "sint-truiden": "Sint-Truidense VV.png",
        "stvv": "Sint-Truidense VV.png",
        "стандард": "Standard Liège.png",
        "стандард льеж": "Standard Liège.png",
        "standard liege": "Standard Liège.png",
        "standard": "Standard Liège.png",
        "юнион": "Union Saint-Gilloise.png",
        "юнион сен-жиллуаз": "Union Saint-Gilloise.png",
        "union saint-gilloise": "Union Saint-Gilloise.png",
        "saint-gilloise": "Union Saint-Gilloise.png",
    },
    "Ukraine - Premier Liga": {
        "шахтер": "Shakhtar Donetsk.png",
        "шахтер донецк": "Shakhtar Donetsk.png",
        "shakhtar": "Shakhtar Donetsk.png",
        "shakhtar donetsk": "Shakhtar Donetsk.png",
        "динамо киев": "Dynamo Kyiv.png",
        "динамо": "Dynamo Kyiv.png",
        "dynamo kyiv": "Dynamo Kyiv.png",
        "dynamo": "Dynamo Kyiv.png",
        "чорноморец": "Chornomorets Odesa.png",
        "chornomorets": "Chornomorets Odesa.png",
        "олександрия": "FC Oleksandriya.png",
        "oleksandriya": "FC Oleksandriya.png",
        "ингулец": "Ingulets Petrove.png",
        "ingulets": "Ingulets Petrove.png",
        "карпаты": "Karpaty Lviv.png",
        "karpaty": "Karpaty Lviv.png",
        "колос": "Kolos Kovalivka.png",
        "kolos": "Kolos Kovalivka.png",
        "кривбасс": "Kryvbas Kryvyi Rig.png",
        "kryvbas": "Kryvbas Kryvyi Rig.png",
        "лнз черкассы": "LNZ Cherkasy.png",
        "lnz": "LNZ Cherkasy.png",
        "левый берег": "Livyi Bereg Kyiv.png",
        "livyi bereg": "Livyi Bereg Kyiv.png",
        "верес": "NK Veres Rivne.png",
        "veres": "NK Veres Rivne.png",
        "оболонь": "Obolon Kyiv.png",
        "obolon": "Obolon Kyiv.png",
        "полесье": "Polissya Zhytomyr.png",
        "polissya": "Polissya Zhytomyr.png",
        "рух": "Rukh Lviv.png",
        "rukh": "Rukh Lviv.png",
        "ворскла": "Vorskla Poltava.png",
        "vorskla": "Vorskla Poltava.png",
        "зоря": "Zorya Lugansk.png",
        "zorya": "Zorya Lugansk.png",
    },
    "England - Premier League": {
        "арсенал": "Arsenal FC.png",
        "арсенал лондон": "Arsenal FC.png",
        "arsenal": "Arsenal FC.png",
        "arsenal fc": "Arsenal FC.png",
        "челси": "Chelsea FC.png",
        "chelsea": "Chelsea FC.png",
        "chelsea fc": "Chelsea FC.png",
        "манчестер юнайтед": "Manchester United.png",
        "manchester united": "Manchester United.png",
        "манчестер сити": "Manchester City.png",
        "manchester city": "Manchester City.png",
        "ливерпуль": "Liverpool FC.png",
        "liverpool": "Liverpool FC.png",
        "liverpool fc": "Liverpool FC.png",
        "бурнмут": "AFC Bournemouth.png",
        "bournemouth": "AFC Bournemouth.png",
        "астон вилла": "Aston Villa.png",
        "вилла": "Aston Villa.png",
        "aston villa": "Aston Villa.png",
        "брентфорд": "Brentford FC.png",
        "brentford": "Brentford FC.png",
        "брайтон": "Brighton & Hove Albion.png",
        "brighton": "Brighton & Hove Albion.png",
        "кристал пэлас": "Crystal Palace.png",
        "crystal palace": "Crystal Palace.png",
        "эвертон": "Everton FC.png",
        "everton": "Everton FC.png",
        "фулхэм": "Fulham FC.png",
        "fulham": "Fulham FC.png",
        "ипсвич": "Ipswich Town.png",
        "ipswich": "Ipswich Town.png",
        "лестер": "Leicester City.png",
        "leicester": "Leicester City.png",
        "ньюкасл": "Newcastle United.png",
        "newcastle": "Newcastle United.png",
        "ноттингем": "Nottingham Forest.png",
        "nottingham forest": "Nottingham Forest.png",
        "саутгемптон": "Southampton FC.png",
        "southampton": "Southampton FC.png",
        "тоттенхэм": "Tottenham Hotspur.png",
        "tottenham": "Tottenham Hotspur.png",
        "вест хэм": "West Ham United.png",
        "west ham": "West Ham United.png",
        "вольверхэмптон": "Wolverhampton Wanderers.png",
        "wolves": "Wolverhampton Wanderers.png",
    },
    "Spain - LaLiga": {
        "барселона": "FC Barcelona.png",
        "барса": "FC Barcelona.png",
        "barcelona": "FC Barcelona.png",
        "fc barcelona": "FC Barcelona.png",
        "реал мадрид": "Real Madrid.png",
        "real madrid": "Real Madrid.png",
        "атлетико мадрид": "Atlético de Madrid.png",
        "atletico madrid": "Atlético de Madrid.png",
        "севилья": "Sevilla FC.png",
        "sevilla": "Sevilla FC.png",
        "реал бетис": "Real Betis Balompié.png",
        "real betis": "Real Betis Balompié.png",
        "вильярреал": "Villarreal CF.png",
        "villarreal": "Villarreal CF.png",
        "валенсия": "Valencia CF.png",
        "valencia": "Valencia CF.png",
        "атлетик бильбао": "Athletic Bilbao.png",
        "athletic bilbao": "Athletic Bilbao.png",
        "сельта": "Celta de Vigo.png",
        "celta vigo": "Celta de Vigo.png",
        "эспаньол": "RCD Espanyol Barcelona.png",
        "espanyol": "RCD Espanyol Barcelona.png",
        "жирона": "Girona FC.png",
        "girona": "Girona FC.png",
        "майорка": "RCD Mallorca.png",
        "mallorca": "RCD Mallorca.png",
        "райо вальекано": "Rayo Vallecano.png",
        "rayo": "Rayo Vallecano.png",
        "реал сосьедад": "Real Sociedad.png",
        "real sociedad": "Real Sociedad.png",
        "реал вальядолид": "Real Valladolid CF.png",
        "valladolid": "Real Valladolid CF.png",
        "лас пальмас": "UD Las Palmas.png",
        "las palmas": "UD Las Palmas.png",
        "осасуна": "CA Osasuna.png",
        "osasuna": "CA Osasuna.png",
        "леганес": "CD Leganés.png",
        "leganes": "CD Leganés.png",
        "алавес": "Deportivo Alavés.png",
        "alaves": "Deportivo Alavés.png",
        "хетафе": "Getafe CF.png",
        "getafe": "Getafe CF.png",
    },
    "Greece - Super League 1": {
        "аек": "AEK Athens.png",
        "aek": "AEK Athens.png",
        "апо левадиакос": "APO Levadiakos.png",
        "levadiakos": "APO Levadiakos.png",
        "арис": "Aris Thessaloniki.png",
        "aris": "Aris Thessaloniki.png",
        "астерас": "Asteras Aktor.png",
        "asteras": "Asteras Aktor.png",
        "каллитея": "Athens Kallithea.png",
        "kallithea": "Athens Kallithea.png",
        "аттромитос": "Atromitos Athens.png",
        "atromitos": "Atromitos Athens.png",
        "офи": "OFI Crete FC.png",
        "ofi": "OFI Crete FC.png",
        "олимпиакос": "Olympiacos Piraeus.png",
        "olympiacos": "Olympiacos Piraeus.png",
        "панатинаикос": "Panathinaikos FC.png",
        "panathinaikos": "Panathinaikos FC.png",
        "панетоликос": "Panetolikos GFS.png",
        "panetolikos": "Panetolikos GFS.png",
        "пансерраикос": "Panserraikos.png",
        "panserraikos": "Panserraikos.png",
        "паок": "PAOK Thessaloniki.png",
        "paok": "PAOK Thessaloniki.png",
        "ламия": "PAS Lamia 1964.png",
        "lamia": "PAS Lamia 1964.png",
        "волос": "Volos NPS.png",
        "volos": "Volos NPS.png",
    },
    "Romania - SuperLiga": {
        "политехника": "ACSM Politehnica Iasi.png",
        "politehnica": "ACSM Politehnica Iasi.png",
        "униреа": "AFC Unirea 04 Slobozia.png",
        "unirea": "AFC Unirea 04 Slobozia.png",
        "чфр клуж": "CFR Cluj.png",
        "cfr": "CFR Cluj.png",
        "университатя": "CS Universitatea Craiova.png",
        "universitatea": "CS Universitatea Craiova.png",
        "ботошань": "FC Botosani.png",
        "botosani": "FC Botosani.png",
        "бузэу": "FC Buzău.png",
        "buzau": "FC Buzău.png",
        "динамо бухарест": "FC Dinamo 1948.png",
        "dinamo": "FC Dinamo 1948.png",
        "херманнштадт": "FC Hermannstadt.png",
        "hermannstadt": "FC Hermannstadt.png",
        "рапид бухарест": "FC Rapid 1923.png",
        "rapid": "FC Rapid 1923.png",
        "университатя клуж": "FC Universitatea Cluj.png",
        "universitatea cluj": "FC Universitatea Cluj.png",
        "стэуа": "FCSB.png",
        "fcsb": "FCSB.png",
        "фарул": "FCV Farul Constanta.png",
        "farul": "FCV Farul Constanta.png",
        "петролул": "Petrolul Ploiesti.png",
        "petrolul": "Petrolul Ploiesti.png",
        "отелул": "SC Otelul Galati.png",
        "otelul": "SC Otelul Galati.png",
        "сепси": "Sepsi OSK Sf. Gheorghe.png",
        "sepsi": "Sepsi OSK Sf. Gheorghe.png",
        "ута": "UTA Arad.png",
        "uta": "UTA Arad.png",
    },
    "Italy - Serie A": {
        "милан": "AC Milan.png",
        "ac milan": "AC Milan.png",
        "milan": "AC Milan.png",
        "интер": "Inter Milan.png",
        "inter milan": "Inter Milan.png",
        "inter": "Inter Milan.png",
        "монца": "AC Monza.png",
        "monza": "AC Monza.png",
        "фиорентина": "ACF Fiorentina.png",
        "fiorentina": "ACF Fiorentina.png",
        "рома": "AS Roma.png",
        "as roma": "AS Roma.png",
        "аталанта": "Atalanta BC.png",
        "atalanta": "Atalanta BC.png",
        "болонья": "Bologna FC 1909.png",
        "bologna": "Bologna FC 1909.png",
        "кальяри": "Cagliari Calcio.png",
        "cagliari": "Cagliari Calcio.png",
        "комо": "Como 1907.png",
        "como": "Como 1907.png",
        "эмполи": "FC Empoli.png",
        "empoli": "FC Empoli.png",
        "дженоа": "Genoa CFC.png",
        "genoa": "Genoa CFC.png",
        "верона": "Hellas Verona.png",
        "hellas verona": "Hellas Verona.png",
        "ювентус": "Juventus FC.png",
        "juventus": "Juventus FC.png",
        "парма": "Parma Calcio 1913.png",
        "parma": "Parma Calcio 1913.png",
        "лацио": "SS Lazio.png",
        "lazio": "SS Lazio.png",
        "наполи": "SSC Napoli.png",
        "napoli": "SSC Napoli.png",
        "торино": "Torino FC.png",
        "torino": "Torino FC.png",
        "удинезе": "Udinese Calcio.png",
        "udinese": "Udinese Calcio.png",
        "лечче": "US Lecce.png",
        "lecce": "US Lecce.png",
        "венеция": "Venezia FC.png",
        "venezia": "Venezia FC.png",
    },
    "Norway - Eliteserien": {
        "будё глимт": "FK Bodø Glimt.png",
        "bodo glimt": "FK Bodø Glimt.png",
        "хёугесунн": "FK Haugesund.png",
        "haugesund": "FK Haugesund.png",
        "фредрикстад": "Fredrikstad FK.png",
        "fredrikstad": "Fredrikstad FK.png",
        "хамаркамератене": "Hamarkameratene.png",
        "hamarkameratene": "Hamarkameratene.png",
        "кфум": "KFUM-Kameratene Oslo.png",
        "kfum": "KFUM-Kameratene Oslo.png",
        "кристиансунн": "Kristiansund BK.png",
        "kristiansund": "Kristiansund BK.png",
        "лиллестрём": "Lillestrøm SK.png",
        "lillestrom": "Lillestrøm SK.png",
        "мольде": "Molde FK.png",
        "molde": "Molde FK.png",
        "одд": "Odds BK.png",
        "odds": "Odds BK.png",
        "росенборг": "Rosenborg BK.png",
        "rosenborg": "Rosenborg BK.png",
        "саннефьорд": "Sandefjord Fotball.png",
        "sandefjord": "Sandefjord Fotball.png",
        "сарпсборг": "Sarpsborg 08 FF.png",
        "sarpsborg": "Sarpsborg 08 FF.png",
        "бранн": "SK Brann.png",
        "brann": "SK Brann.png",
        "стёмсгодсет": "Strømsgodset IF.png",
        "stromsgodset": "Strømsgodset IF.png",
        "тромсё": "Tromsø IL.png",
        "tromso": "Tromsø IL.png",
        "викинг": "Viking FK.png",
        "viking": "Viking FK.png",
    },
    "Croatia - SuperSport HNL": {
        "динамо загреб": "GNK Dinamo Zagreb.png",
        "dinamo zagreb": "GNK Dinamo Zagreb.png",
        "горица": "HNK Gorica.png",
        "gorica": "HNK Gorica.png",
        "хайдук": "HNK Hajduk Split.png",
        "hajduk": "HNK Hajduk Split.png",
        "риека": "HNK Rijeka.png",
        "rijeka": "HNK Rijeka.png",
        "шибеник": "HNK Sibenik.png",
        "sibenik": "HNK Sibenik.png",
        "истра": "NK Istra 1961.png",
        "istra": "NK Istra 1961.png",
        "локомотива": "NK Lokomotiva Zagreb.png",
        "lokomotiva": "NK Lokomotiva Zagreb.png",
        "осиек": "NK Osijek.png",
        "osijek": "NK Osijek.png",
        "вараждин": "NK Varazdin.png",
        "varazdin": "NK Varazdin.png",
        "славен": "Slaven Belupo Koprivnica.png",
        "slaven": "Slaven Belupo Koprivnica.png",
    },
    "Portugal - Liga Portugal": {
        "авеш": "Avs Futebol.png",
        "avs": "Avs Futebol.png",
        "боавишта": "Boavista FC.png",
        "boavista fc": "Boavista FC.png",
        "boavista": "Boavista FC.png",
        "каза пиа": "Casa Pia AC.png",
        "casa pia ac": "Casa Pia AC.png",
        "casa pia": "Casa Pia AC.png",
        "насьонал": "CD Nacional.png",
        "cd nacional": "CD Nacional.png",
        "санта клара": "CD Santa Clara.png",
        "cd santa clara": "CD Santa Clara.png",
        "эстрела": "CF Estrela Amadora.png",
        "cf estrela amadora": "CF Estrela Amadora.png",
        "арука": "FC Arouca.png",
        "fc arouca": "FC Arouca.png",
        "arouca": "FC Arouca.png",
        "фамаликан": "FC Famalicão.png",
        "fc famalicão": "FC Famalicão.png",
        "famalicão": "FC Famalicão.png",
        "порто": "FC Porto.png",
        "fc porto": "FC Porto.png",
        "porto": "FC Porto.png",
        "эшторил": "GD Estoril Praia.png",
        "estoril": "GD Estoril Praia.png",
        "жил висенте": "Gil Vicente FC.png",
        "gil vicente": "Gil Vicente FC.png",
        "морейренсе": "Moreirense FC.png",
        "moreirense": "Moreirense FC.png",
        "риу аве": "Rio Ave FC.png",
        "rio ave": "Rio Ave FC.png",
        "брага": "SC Braga.png",
        "braga": "SC Braga.png",
        "фаренсе": "SC Farense.png",
        "farense": "SC Farense.png",
        "бенфика": "SL Benfica.png",
        "benfica": "SL Benfica.png",
        "спортинг": "Sporting CP.png",
        "sporting": "Sporting CP.png",
        "витория": "Vitória Guimarães SC.png",
        "vitoria guimaraes": "Vitória Guimarães SC.png",
    },
    "Poland - PKO BP Ekstraklasa": {
        "cracovia": "Cracovia.png",
        "gks katowice": "GKS Katowice.png",
        "gornik zabrze": "Górnik Zabrze.png",
        "jagiellonia bialystok": "Jagiellonia Bialystok.png",
        "korona kielce": "Korona Kielce.png",
        "lech poznan": "Lech Poznan.png",
        "lechia gdansk": "Lechia Gdansk.png",
        "legia warszawa": "Legia Warszawa.png",
        "motor lublin": "Motor Lublin.png",
        "piast gliwice": "Piast Gliwice.png",
        "pogon szczecin": "Pogon Szczecin.png",
        "puszcza niepolomice": "Puszcza Niepolomice.png",
        "radomiak radom": "Radomiak Radom.png",
        "rakow częstochowa": "Raków Częstochowa.png",
        "slask wroclaw": "Slask Wroclaw.png",
        "stal mielec": "Stal Mielec.png",
        "widzew lodz": "Widzew Lodz.png",
        "zaglebie lubin": "Zaglebie Lubin.png",
        "warta": "Warta Poznań.png",
        "warta": "Warta Poznań.png",
        "wisla": "Wisła Kraków.png",
        "wisla": "Wisła Kraków.png",
        "wisla plock": "Wisła Płock.png",
        "wisla plock": "Wisła Płock.png",
        "gornik": "Górnik Zabrze.png",
        "gornik": "Górnik Zabrze.png",
        "zaglebie": "Zagłębie Lubin.png",
        "zaglebie": "Zagłębie Lubin.png",
        "cracovia": "Cracovia Kraków.png",
        "cracovia": "Cracovia Kraków.png",
        "legia": "Legia Warszawa.png",
        "legia": "Legia Warszawa.png",
        "lech": "Lech Poznań.png",
        "lech": "Lech Poznań.png",
        "lechia": "Lechia Gdańsk.png",
        "lechia": "Lechia Gdańsk.png",
        "pogon": "Pogoń Szczecin.png",
        "pogon": "Pogoń Szczecin.png",
        "radomiak": "Radomiak Radom.png",
        "radomiak": "Radomiak Radom.png",
        "ruch": "Ruch Chorzów.png",
        "ruch": "Ruch Chorzów.png",
        "stal": "Stal Mielec.png",
        "stal": "Stal Mielec.png",
        "slask": "Śląsk Wrocław.png",
        "slask": "Śląsk Wrocław.png",
        "jagiellonia": "Jagiellonia Białystok.png",
        "jagiellonia": "Jagiellonia Białystok.png",
    },
    "Sweden - Allsvenskan": {
        "айк": "AIK.png",
        "aik": "AIK.png",
        "хекен": "BK Häcken.png",
        "hacken": "BK Häcken.png",
        "юргорден": "Djurgårdens IF.png",
        "djurgarden": "Djurgårdens IF.png",
        "гаис": "GAIS.png",
        "gais": "GAIS.png",
        "халмстад": "Halmstads BK.png",
        "halmstad": "Halmstads BK.png",
        "хаммарбю": "Hammarby IF.png",
        "hammarby": "Hammarby IF.png",
        "броммапойкарна": "IF Brommapojkarna.png",
        "brommapojkarna": "IF Brommapojkarna.png",
        "эльфсборг": "IF Elfsborg.png",
        "elfsborg": "IF Elfsborg.png",
        "гётеборг": "IFK Göteborg.png",
        "goteborg": "IFK Göteborg.png",
        "нorrчёпинг": "IFK Norrköping.png",
        "norrkoping": "IFK Norrköping.png",
        "вэрнамо": "IFK Värnamo.png",
        "varnamo": "IFK Värnamo.png",
        "сириус": "IK Sirius.png",
        "sirius": "IK Sirius.png",
        "кальмар": "Kalmar FF.png",
        "kalmar": "Kalmar FF.png",
        "мольмё": "Malmö FF.png",
        "malmo": "Malmö FF.png",
        "мьельбю": "Mjällby AIF.png",
        "mjallby": "Mjällby AIF.png",
        "вестерос": "Västerås SK.png",
        "vasteras": "Västerås SK.png",
    },
    "France - Ligue 1": {
        "оксер": "AJ Auxerre.png",
        "auxerre": "AJ Auxerre.png",
        "анже": "Angers SCO.png",
        "angers": "Angers SCO.png",
        "монaco": "AS Monaco.png",
        "monaco": "AS Monaco.png",
        "сен-этьен": "AS Saint-Étienne.png",
        "saint-etienne": "AS Saint-Étienne.png",
        "нант": "FC Nantes.png",
        "nantes": "FC Nantes.png",
        "тулуза": "FC Toulouse.png",
        "toulouse": "FC Toulouse.png",
        "гавр": "Le Havre AC.png",
        "le havre": "Le Havre AC.png",
        "лиль": "LOSC Lille.png",
        "lille": "LOSC Lille.png",
        "монпелье": "Montpellier HSC.png",
        "montpellier": "Montpellier HSC.png",
        "ницца": "OGC Nice.png",
        "nice": "OGC Nice.png",
        "лион": "Olympique Lyon.png",
        "lyon": "Olympique Lyon.png",
        "марсель": "Olympique Marseille.png",
        "marseille": "Olympique Marseille.png",
        "псж": "Paris Saint-Germain.png",
        "пари сен-жермен": "Paris Saint-Germain.png",
        "paris sg": "Paris Saint-Germain.png",
        "ленс": "RC Lens.png",
        "lens": "RC Lens.png",
        "страсбур": "RC Strasbourg Alsace.png",
        "strasbourg": "RC Strasbourg Alsace.png",
        "брест": "Stade Brestois 29.png",
        "brest": "Stade Brestois 29.png",
        "реймс": "Stade Reims.png",
        "reims": "Stade Reims.png",
        "ренн": "Stade Rennais FC.png",
        "rennes": "Stade Rennais FC.png",
    },
    "Serbia - Super liga Srbije": {
        "чукарички": "FK Cukaricki.png",
        "cukaricki": "FK Cukaricki.png",
        "имт": "FK IMT Belgrad.png",
        "imt": "FK IMT Belgrad.png",
        "единиство": "FK Jedinstvo Ub.png",
        "jedinstvo": "FK Jedinstvo Ub.png",
        "младост": "FK Mladost Lucani.png",
        "mladost": "FK Mladost Lucani.png",
        "напредак": "FK Napredak Krusevac.png",
        "napredak": "FK Napredak Krusevac.png",
        "нови пазар": "FK Novi Pazar.png",
        "novi pazar": "FK Novi Pazar.png",
        "партизан": "FK Partizan Belgrade.png",
        "partizan": "FK Partizan Belgrade.png",
        "раднички": "FK Radnicki 1923 Kragujevac.png",
        "radnicki": "FK Radnicki 1923 Kragujevac.png",
        "раднички ниш": "FK Radnicki Nis.png",
        "radnicki nis": "FK Radnicki Nis.png",
        "спартак": "FK Spartak Subotica.png",
        "spartak": "FK Spartak Subotica.png",
        "текстилац": "FK Tekstilac Odzaci.png",
        "tekstilac": "FK Tekstilac Odzaci.png",
        "тсц": "FK TSC Backa Topola.png",
        "tsc": "FK TSC Backa Topola.png",
        "войводина": "FK Vojvodina Novi Sad.png",
        "vojvodina": "FK Vojvodina Novi Sad.png",
        "офк": "OFK Beograd.png",
        "ofk": "OFK Beograd.png",
        "црвена звезда": "Red Star Belgrade.png",
        "red star": "Red Star Belgrade.png",
        "железничар": "Zeleznicar Pancevo.png",
        "zeleznicar": "Zeleznicar Pancevo.png",
    },
    "Türkiye - Süper Lig": {
        "adana demirspor": "Adana Demirspor.png",
        "adana": "Adana Demirspor.png",
        "алания": "Alanyaspor.png",
        "alanya": "Alanyaspor.png",
        "анкара": "Ankaragücü.png",
        "ankaragucu": "Ankaragücü.png",
        "анталья": "Antalyaspor.png",
        "antalya": "Antalyaspor.png",
        "бешикташ": "Beşiktaş JK.png",
        "besiktas": "Beşiktaş JK.png",
        "галатасарай": "Galatasaray SK.png",
        "galatasaray": "Galatasaray SK.png",
        "газиантеп": "Gaziantep FK.png",
        "gaziantep": "Gaziantep FK.png",
        "хатайспор": "Hatayspor.png",
        "hatay": "Hatayspor.png",
        "истанбул": "İstanbul Başakşehir FK.png",
        "istanbul": "İstanbul Başakşehir FK.png",
        "истанбулспор": "İstanbulspor.png",
        "istanbulspor": "İstanbulspor.png",
        "кайсери": "Kayserispor.png",
        "kayseri": "Kayserispor.png",
        "касымпаша": "Kasımpaşa SK.png",
        "kasimpasa": "Kasımpaşa SK.png",
        "конья": "Konyaspor.png",
        "konya": "Konyaspor.png",
        "пендикспор": "Pendikspor.png",
        "pendik": "Pendikspor.png",
        "ризеспор": "Rizespor.png",
        "rize": "Rizespor.png",
        "самсунспор": "Samsunspor.png",
        "samsun": "Samsunspor.png",
        "сивасспор": "Sivasspor.png",
        "sivas": "Sivasspor.png",
        "трабзонспор": "Trabzonspor.png",
        "trabzon": "Trabzonspor.png",
    },
    "Scotland - Scottish Premiership": {
        "абердин": "Aberdeen FC.png",
        "aberdeen": "Aberdeen FC.png",
        "селтик": "Celtic FC.png",
        "celtic": "Celtic FC.png",
        "данди": "Dundee FC.png",
        "dundee": "Dundee FC.png",
        "данди юнайтед": "Dundee United FC.png",
        "dundee united": "Dundee United FC.png",
        "хартс": "Heart of Midlothian FC.png",
        "hearts": "Heart of Midlothian FC.png",
        "хиберниан": "Hibernian FC.png",
        "hibernian": "Hibernian FC.png",
        "килмарнок": "Kilmarnock FC.png",
        "kilmarnock": "Kilmarnock FC.png",
        "мадервелл": "Motherwell FC.png",
        "motherwell": "Motherwell FC.png",
        "рейнджерс": "Rangers FC.png",
        "rangers": "Rangers FC.png",
        "росс каунти": "Ross County FC.png",
        "ross county": "Ross County FC.png",
        "сент джонстон": "St. Johnstone FC.png",
        "st. johnstone": "St. Johnstone FC.png",
        "сент миррен": "St. Mirren FC.png",
        "st. mirren": "St. Mirren FC.png",
    },
    "Hungary - Nemzeti Bajnokság": {
        "дебрецен": "Debreceni VSC.png",
        "debrecen": "Debreceni VSC.png",
        "дьёр": "Diósgyőri VTK.png",
        "diosgyor": "Diósgyőri VTK.png",
        "дьёр": "ETO FC Győr.png",
        "gyor": "ETO FC Győr.png",
        "фехервар": "Fehérvár FC.png",
        "fehervar": "Fehérvár FC.png",
        "ференцварош": "Ferencvárosi TC.png",
        "ferencvaros": "Ferencvárosi TC.png",
        "кечкемет": "Kecskeméti TE.png",
        "kecskemet": "Kecskeméti TE.png",
        "мтк": "MTK Budapest.png",
        "mtk": "MTK Budapest.png",
        "ньиредьхаза": "Nyíregyháza Spartacus.png",
        "nyiregyhaza": "Nyíregyháza Spartacus.png",
        "пакс": "Paksi FC.png",
        "paks": "Paksi FC.png",
        "пушкаш": "Puskás Akadémia FC.png",
        "puskas": "Puskás Akadémia FC.png",
        "залаэгерсег": "Zalaegerszegi TE FC.png",
        "zalaegerszeg": "Zalaegerszegi TE FC.png",
        "уйпешт": "Újpest FC.png",
        "ujpest": "Újpest FC.png",
    },
    "Bulgaria - efbet Liga": {
        "арда": "Arda Kardzhali.png",
        "arda": "Arda Kardzhali.png",
        "берое": "Beroe Stara Zagora.png",
        "beroe": "Beroe Stara Zagora.png",
        "ботев пловдив": "Botev Plovdiv.png",
        "botev plovdiv": "Botev Plovdiv.png",
        "ботев враца": "Botev Vratsa.png",
        "botev vratsa": "Botev Vratsa.png",
        "черно море": "Cherno More Varna.png",
        "cherno more": "Cherno More Varna.png",
        "цска 1948": "CSKA 1948.png",
        "cska 1948": "CSKA 1948.png",
        "цска софия": "CSKA-Sofia.png",
        "cska sofia": "CSKA-Sofia.png",
        "хебар": "Hebar Pazardzhik.png",
        "hebar": "Hebar Pazardzhik.png",
        "крумовград": "Krumovgrad.png",
        "krumovgrad": "Krumovgrad.png",
        "левски": "Levski Sofia.png",
        "levski": "Levski Sofia.png",
        "локомотив пловдив": "Lokomotiv Plovdiv.png",
        "lokomotiv plovdiv": "Lokomotiv Plovdiv.png",
        "локомотив софия": "Lokomotiv Sofia.png",
        "lokomotiv sofia": "Lokomotiv Sofia.png",
        "лудогорец": "Ludogorets Razgrad.png",
        "ludogorets": "Ludogorets Razgrad.png",
        "сентябри": "Septemvri Sofia.png",
        "septemvri": "Septemvri Sofia.png",
        "славия": "Slavia Sofia.png",
        "slavia": "Slavia Sofia.png",
        "спартак варна": "Spartak Varna.png",
        "spartak varna": "Spartak Varna.png",
    },
    "Germany - Bundesliga": {
        "хайденхайм": "1.FC Heidenheim 1846.png",
        "heidenheim": "1.FC Heidenheim 1846.png",
        "унион берлин": "1.FC Union Berlin.png",
        "union berlin": "1.FC Union Berlin.png",
        "майнц": "1.FSV Mainz 05.png",
        "mainz": "1.FSV Mainz 05.png",
        "байер леверкузен": "Bayer 04 Leverkusen.png",
        "leverkusen": "Bayer 04 Leverkusen.png",
        "бавария": "Bayern Munich.png",
        "bayern": "Bayern Munich.png",
        "дортмунд": "Borussia Dortmund.png",
        "dortmund": "Borussia Dortmund.png",
        "боруссия мёнхенгладбах": "Borussia Mönchengladbach.png",
        "mönchengladbach": "Borussia Mönchengladbach.png",
        "айнтрахт франкфурт": "Eintracht Frankfurt.png",
        "frankfurt": "Eintracht Frankfurt.png",
        "аугсбург": "FC Augsburg.png",
        "augsburg": "FC Augsburg.png",
        "санкт-паули": "FC St. Pauli.png",
        "st. pauli": "FC St. Pauli.png",
        "киль": "Holstein Kiel.png",
        "kiel": "Holstein Kiel.png",
        "рб лейпциг": "RB Leipzig.png",
        "leipzig": "RB Leipzig.png",
        "фрайбург": "SC Freiburg.png",
        "freiburg": "SC Freiburg.png",
        "вердер": "SV Werder Bremen.png",
        "werder bremen": "SV Werder Bremen.png",
        "хоффенхайм": "TSG 1899 Hoffenheim.png",
        "hoffenheim": "TSG 1899 Hoffenheim.png",
        "штутгарт": "VfB Stuttgart.png",
        "stuttgart": "VfB Stuttgart.png",
        "бохум": "VfL Bochum.png",
        "bochum": "VfL Bochum.png",
        "вольфсбург": "VfL Wolfsburg.png",
        "wolfsburg": "VfL Wolfsburg.png",
    },
    "Denmark - Superliga": {
        "aalborg bk": "Aalborg BK.png",
        "aarhus gf": "Aarhus GF.png",
        "brondby if": "Bröndby IF.png",
        "fc copenhagen": "FC Copenhagen.png",
        "fc midtjylland": "FC Midtjylland.png",
        "fc nordsjaelland": "FC Nordsjaelland.png",
        "lyngby bk": "Lyngby BK.png",
        "randers fc": "Randers FC.png",
        "silkeborg if": "Silkeborg IF.png",
        "sonderjyske": "Sönderjyske.png",
        "vejle boldklub": "Vejle Boldklub.png",
        "viborg ff": "Viborg FF.png",
        "альборг": "Aalborg BK.png",
        "aalborg": "Aalborg BK.png",
        "брондбю": "Brøndby IF.png",
        "brondby": "Brøndby IF.png",
        "хобро": "Hobro IK.png",
        "hobro": "Hobro IK.png",
        "хорсенс": "AC Horsens.png",
        "horsens": "AC Horsens.png",
        "кёге": "HB Køge.png",
        "koge": "HB Køge.png",
        "копенгаген": "FC Copenhagen.png",
        "copenhagen": "FC Copenhagen.png",
        "мидтьюлланн": "FC Midtjylland.png",
        "midtjylland": "FC Midtjylland.png",
        "норшелланн": "FC Nordsjælland.png",
        "nordsjaelland": "FC Nordsjælland.png",
        "раннерс": "Randers FC.png",
        "randers": "Randers FC.png",
        "силькеборг": "Silkeborg IF.png",
        "silkeborg": "Silkeborg IF.png",
        "вейле": "Vejle Boldklub.png",
        "vejle": "Vejle Boldklub.png",
        "виборг": "Viborg FF.png",
        "viborg": "Viborg FF.png",
    },
    "Netherlands - Eredivisie": {
        "аякс": "Ajax Amsterdam.png",
        "ajax": "Ajax Amsterdam.png",
        "алмере": "Almere City FC.png",
        "almere city": "Almere City FC.png",
        "аз": "AZ Alkmaar.png",
        "az alkmaar": "AZ Alkmaar.png",
        "гронинген": "FC Groningen.png",
        "groningen": "FC Groningen.png",
        "утрехт": "FC Utrecht.png",
        "utrecht": "FC Utrecht.png",
        "фейеноорд": "Feyenoord Rotterdam.png",
        "feyenoord": "Feyenoord Rotterdam.png",
        "фортуна": "Fortuna Sittard.png",
        "fortuna": "Fortuna Sittard.png",
        "гоу ахед": "Go Ahead Eagles.png",
        "go ahead": "Go Ahead Eagles.png",
        "хераклес": "Heracles Almelo.png",
        "heracles": "Heracles Almelo.png",
        "нак": "NAC Breda.png",
        "nac breda": "NAC Breda.png",
        "нек": "NEC Nijmegen.png",
        "nec": "NEC Nijmegen.png",
        "пек": "PEC Zwolle.png",
        "pec zwolle": "PEC Zwolle.png",
        "псв": "PSV Eindhoven.png",
        "psv": "PSV Eindhoven.png",
        "ркк": "RKC Waalwijk.png",
        "rkc": "RKC Waalwijk.png",
        "хееренвеен": "SC Heerenveen.png",
        "heerenveen": "SC Heerenveen.png",
        "спарта": "Sparta Rotterdam.png",
        "sparta": "Sparta Rotterdam.png",
        "твенте": "Twente Enschede FC.png",
        "twente": "Twente Enschede FC.png",
        "виллем ii": "Willem II Tilburg.png",
        "willem ii": "Willem II Tilburg.png",
    },
    "Czech Republic - Chance Liga": {
        "баник": "Baník Ostrava.png",
        "banik": "Baník Ostrava.png",
        "бохемианс": "Bohemians 1905.png",
        "bohemians": "Bohemians 1905.png",
        "динамо ческе": "Dynamo České Budějovice.png",
        "dynamo ceske": "Dynamo České Budějovice.png",
        "гавиржов": "FC Hradec Králové.png",
        "hradec kralove": "FC Hradec Králové.png",
        "карвина": "FC Karviná.png",
        "karvina": "FC Karviná.png",
        "либерец": "FC Slovan Liberec.png",
        "liberec": "FC Slovan Liberec.png",
        "зброёвка": "FC Zbrojovka Brno.png",
        "zbrojovka": "FC Zbrojovka Brno.png",
        "яблонец": "FK Jablonec.png",
        "jablonec": "FK Jablonec.png",
        "млада болеслав": "FK Mladá Boleslav.png",
        "mlada boleslav": "FK Mladá Boleslav.png",
        "пальфи": "FK Pardubice.png",
        "pardubice": "FK Pardubice.png",
        "теплице": "FK Teplice.png",
        "teplice": "FK Teplice.png",
        "виктория": "FK Viktoria Plzeň.png",
        "viktoria plzen": "FK Viktoria Plzeň.png",
        "словацко": "1.FC Slovacko.png",
        "slovacko": "1.FC Slovacko.png",
        "славия": "SK Slavia Prague.png",
        "slavia": "SK Slavia Prague.png",
        "спарта": "Sparta Prague.png",
        "sparta": "Sparta Prague.png",
    },
    "Russia - Premier Liga": {
        "ахмат": "Akhmat Grozny.png",
        "akhmat": "Akhmat Grozny.png",
        "акрон": "Akron Togliatti.png",
        "akron": "Akron Togliatti.png",
        "цска": "CSKA Moscow.png",
        "cska": "CSKA Moscow.png",
        "динамо махачкала": "Dinamo Makhachkala.png",
        "dinamo makhachkala": "Dinamo Makhachkala.png",
        "динамо москва": "Dynamo Moscow.png",
        "dynamo moscow": "Dynamo Moscow.png",
        "факел": "Fakel Voronezh.png",
        "fakel": "Fakel Voronezh.png",
        "химки": "FC Khimki.png",
        "khimki": "FC Khimki.png",
        "краснодар": "FC Krasnodar.png",
        "krasnodar": "FC Krasnodar.png",
        "оренбург": "FC Orenburg.png",
        "orenburg": "FC Orenburg.png",
        "пари нн": "FC Pari Nizhniy Novgorod.png",
        "pari nn": "FC Pari Nizhniy Novgorod.png",
        "ростов": "FC Rostov.png",
        "rostov": "FC Rostov.png",
        "крылья советов": "Krylya Sovetov Samara.png",
        "krylya sovetov": "Krylya Sovetov Samara.png",
        "локомотив": "Lokomotiv Moscow.png",
        "lokomotiv": "Lokomotiv Moscow.png",
        "рубин": "Rubin Kazan.png",
        "rubin": "Rubin Kazan.png",
        "спартак": "Spartak Moscow.png",
        "spartak": "Spartak Moscow.png",
        "зенит": "Zenit St. Petersburg.png",
        "zenit": "Zenit St. Petersburg.png",
    },
    "Switzerland - Super League": {
        "янг бойз": "BSC Young Boys.png",
        "young boys": "BSC Young Boys.png",
        "базель": "FC Basel 1893.png",
        "basel": "FC Basel 1893.png",
        "лозанна": "FC Lausanne-Sport.png",
        "lausanne": "FC Lausanne-Sport.png",
        "лугано": "FC Lugano.png",
        "lugano": "FC Lugano.png",
        "люцерн": "FC Luzern.png",
        "luzern": "FC Luzern.png",
        "сион": "FC Sion.png",
        "sion": "FC Sion.png",
        "санкт-галлен": "FC St. Gallen 1879.png",
        "st. gallen": "FC St. Gallen 1879.png",
        "винтертур": "FC Winterthur.png",
        "winterthur": "FC Winterthur.png",
        "цюрих": "FC Zürich.png",
        "zurich": "FC Zürich.png",
        "грассхоппер": "Grasshopper Club Zurich.png",
        "grasshopper": "Grasshopper Club Zurich.png",
        "серветт": "Servette FC.png",
        "servette": "Servette FC.png",
        "ивердон": "Yverdon Sport FC.png",
        "yverdon": "Yverdon Sport FC.png",
    },
}

def generate_full_team_mappings() -> Dict[str, str]:
    """
    Генерирует полную карту соответствий названий команд и файлов с логотипами.
    
    Returns:
        Словарь с маппингами вида {team_name: logo_file}
    """
    full_mappings = {}
    for league, teams in LEAGUE_TEAMS_MAPPINGS.items():
        for team_name, logo_file in teams.items():
            full_mappings[team_name.lower()] = logo_file
    return full_mappings

def get_league_teams(league_folder: str) -> List[str]:
    """
    Получает список команд из указанной лиги.
    
    Args:
        league_folder: Название папки лиги (например, 'Spain - LaLiga')
    
    Returns:
        Список названий команд (без расширений файлов)
    """
    teams = []
    league_path = os.path.join(LOGOS_FOLDER, league_folder)
    try:
        if os.path.exists(league_path):
            for filename in os.listdir(league_path):
                if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
                    team_name = os.path.splitext(filename)[0]
                    teams.append(team_name)
        else:
            logger.warning(f"Папка лиги {league_path} не найдена")
    except Exception as e:
        logger.error(f"Ошибка при получении списка команд из {league_folder}: {e}")
    return teams

def load_team_mappings_from_logos() -> Dict[str, str]:
    """
    Загружает маппинги из папки с логотипами.
    
    Returns:
        Словарь с маппингами вида {team_name: logo_file}
    """
    mappings = {}
    try:
        for filename in os.listdir(LOGOS_FOLDER):
            if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
                team_name = os.path.splitext(filename)[0]
                # Убираем префикс лиги, если он есть
                if '_' in team_name:
                    team_name = team_name.split('_', 1)[1]
                mappings[team_name.lower()] = filename
                # Добавляем варианты без префиксов/суффиксов
                parts = team_name.split()
                if len(parts) > 1:
                    if parts[0].lower() in ['fc', 'ac', 'sc', 'sk']:
                        mappings[' '.join(parts[1:]).lower()] = filename
                    if parts[-1].lower() in ['fc', 'ac', 'sc', 'sk', 'united', 'city']:
                        mappings[' '.join(parts[:-1]).lower()] = filename
    except Exception as e:
        logger.error(f"Ошибка при загрузке маппингов команд: {e}")
    return mappings

def get_extended_team_mappings() -> Dict[str, str]:
    """
    Получает расширенные маппинги команд, объединяя предопределенные и автоматически сгенерированные.
    
    Returns:
        Словарь с полными маппингами всех команд
    """
    predefined_mappings = generate_full_team_mappings()
    auto_mappings = load_team_mappings_from_logos()
    # Предопределенные маппинги имеют приоритет
    combined_mappings = {**auto_mappings, **predefined_mappings}
    return combined_mappings

def get_available_leagues() -> List[str]:
    """
    Возвращает список доступных лиг из маппингов.
    
    Returns:
        Список названий лиг
    """
    return sorted(LEAGUE_TEAMS_MAPPINGS.keys())

# Создаем основной словарь маппингов
TEAM_MAPPINGS = generate_full_team_mappings() 